version: "3"

services:
    jenkins:
        build: 
         context: .
         dockerfile: Dockerfile
        container_name: jenkins-master
        image: jenkins-dind
        command: tail -f /dev/null
        ports: 
            - '8081:8080'
            - '50001:50000'
        volumes: 
            - jenkins_home:/var/jenkins_home
            - some-docker-certs-ca:/certs/ca
            - some-docker-certs-client:/certs/client 
            # - /var/run/docker.sock:/var/run/docker.sock
        restart: always


volumes: 
    jenkins_home:
    some-docker-certs-ca:
    some-docker-certs-client:



#   docker run --privileged --name some-docker -d \
#     -e DOCKER_TLS_CERTDIR=/certs \
#     -v some-docker-certs-ca:/certs/ca \
#     -v some-docker-certs-client:/certs/client \
#     docker:dind


# docker run -it --privileged cruizba/ubuntu-dind
