version: "3"

services:
    jenkins:
        container_name: jenkins-dind
        image: yossie17/jenkinsdocker_ubuntudind:v2
        ports: 
            - '8080:8080'
            - '50000:50000'
        volumes: 
            - jenkins_home:/root/.jenkins
        restart: always
        privileged: true
        # command: ["startup.sh]



volumes: 
    jenkins_home:
