version: "3"

services:
    jenkins:
        container_name: jenkins-master
        image: jenkins/jenkins:lts
        ports: 
            - '8080:8080'
            - '50000:50000'
        volumes: 
            - jenkins_home:/var/jenkins_home
        restart: always


volumes: 
    jenkins_home:

