version: "3"

services:
    jenkins:
        container_name: jenkins-master
        image: yossie17/jenkinsdocker_ubuntudind:v1
        ports: 
            - '8080:8080'
            - '50000:50000'
        volumes: 
            - jenkins_home:/var/jenkins_home
        restart: always
        privileged: true
        # command: ["startup.sh]



volumes: 
    jenkins_home:
